version: '3'

services:
  mongodb:
    image: mongodb/mongodb-community-server
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234567890