version: '3'

services:
  redpanda:
    command:
      - redpanda
      - start
      - --smp=1
      - --reserve-memory=0M
      - --overprovisioned
      - --node-id=0
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:19092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:19092
    image: redpandadata/redpanda:latest
    ports:
      - "19092:19092"

  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address ":9001"

  kowl:
    image: quay.io/cloudhut/kowl:v1.4.0
    environment:
      - KAFKA_BROKERS=redpanda:29092
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - redpanda
